#pragma once

#define DRIVER_TAG '5iiv'
#define DEVICE_NAME L"\\Device\\RustCR3Driver"
#define SYM_LINK L"\\DosDevices\\RustCR3Driver"

// IOCTL Control Codes
#define IOCTL_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_BASE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Process names
#define RUST_PROCESS_NAME L"RustClient.exe"
#define GAME_ASSEMBLY_DLL L"GameAssembly.dll"